### ISSUE TITLE
EventEmitter memory leak detected.

### ISSUE THREAD

**Issue by ultimatelocal** [ronco/ember-cli-meta-tags#68]
Good day, 

I'm getting this warning message whenever I'm starting my `ember server` and I don't know what causes `ember-cli-meta-tags` to ask for more listeners but for now, I'm using this quick fix  `process.setMaxListeners(21)` on my `ember-cli-build.js`.

The warning goes away when I have `process.setMaxListeners(21)`. Is this the right approach?

https://github.com/ember-cli/ember-cli/pull/5987 is also suggesting to increase `process.setMaxListeners`. 

```
(node) warning: possible EventEmitter memory leak detected. 11 exit listeners added. Use emitter.setMaxListeners() to increase limit.
Trace
    at process.addListener (events.js:239:17)
    at Object.<anonymous> (/Users/jake/Sites/pizza-ordering/client/node_modules/ember-cli-meta-tags/node_modules/ember-cli-babel/node_modules/broccoli-babel-transpiler/node_modules/broccoli-merge-trees/node_modules/can-symlink/node_modules/tmp/lib/tmp.js:449:9)
    at Module._compile (module.js:434:26)
    at Object.Module._extensions..js (module.js:452:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/jake/Sites/pizza-ordering/client/node_modules/ember-cli-meta-tags/node_modules/ember-cli-babel/node_modules/broccoli-babel-transpiler/node_modules/broccoli-merge-trees/node_modules/can-symlink/index.js:1:73)
    at Module._compile (module.js:434:26)
```

and here's my package.json for reference

```
{
  "name": "client",
  "version": "0.0.0",
  "description": "Small description for client goes here",
  "private": true,
  "directories": {
    "doc": "doc",
    "test": "tests"
  },
  "scripts": {
    "start": "ember server",
    "build": "ember build",
    "test": "ember test"
  },
  "repository": "",
  "engines": {
    "node": ">= 0.10.0"
  },
  "author": "",
  "license": "MIT",
  "devDependencies": {
    "adyen-cse-js": "^0.1.19",
    "broccoli-asset-rev": "^2.4.2",
    "ember-ajax": "^2.0.1",
    "ember-browserify": "^1.1.13",
    "ember-cli": "2.6.2",
    "ember-cli-app-version": "^1.0.0",
    "ember-cli-babel": "^5.1.6",
    "ember-cli-blanket": "0.7.0",
    "ember-cli-clipboard": "0.4.0",
    "ember-cli-content-security-policy": "0.4.0",
    "ember-cli-dependency-checker": "^1.2.0",
    "ember-cli-deploy": "^0.5.1",
    "ember-cli-deploy-build": "0.1.0",
    "ember-cli-deploy-display-revisions": "0.1.0",
    "ember-cli-deploy-gzip": "0.1.1",
    "ember-cli-deploy-manifest": "0.1.1",
    "ember-cli-deploy-redis": "0.1.1",
    "ember-cli-deploy-revision-data": "0.3.2",
    "ember-cli-deploy-rollbar": "1.0.2",
    "ember-cli-deploy-s3": "0.2.0",
    "ember-cli-deploy-slack": "0.1.0",
    "ember-cli-dotenv": "1.0.4",
    "ember-cli-fastclick": "1.1.0",
    "ember-cli-flash": "1.3.15",
    "ember-cli-htmlbars": "^1.0.3",
    "ember-cli-htmlbars-inline-precompile": "^0.3.1",
    "ember-cli-ic-ajax": "0.2.5",
    "ember-cli-inject-live-reload": "^1.4.0",
    "ember-cli-jshint": "^1.0.0",
    "ember-cli-maskedinput": "0.1.1",
    "ember-cli-meta-tags": "4.0.0",
    "ember-cli-mirage": "0.2.0-beta.5",
    "ember-cli-moment-shim": "3.5.0",
    "ember-cli-pace": "0.0.15",
    "ember-cli-page-object": "1.1.0",
    "ember-cli-qunit": "^1.4.0",
    "ember-cli-release": "^0.2.9",
    "ember-cli-sri": "^2.1.0",
    "ember-cli-styles-reloader": "^0.1.6",
    "ember-cli-stylus": "1.0.5",
    "ember-cli-uglify": "^1.2.0",
    "ember-data": "2.6.2",
    "ember-export-application-global": "^1.0.5",
    "ember-font-awesome": "2.1.1",
    "ember-link-action": "0.0.38",
    "ember-load-initializers": "^0.5.1",
    "ember-metrics": "0.5.3",
    "ember-moment": "4.1.0",
    "ember-pikaday": "2.2.4",
    "ember-pluralize": "0.2.0",
    "ember-radio-button": "1.0.7",
    "ember-resolver": "^2.0.3",
    "ember-responsive": "1.2.6",
    "ember-route-action-helper": "0.3.0",
    "ember-tether": "0.3.1",
    "ember-tooltips": "1.0.0",
    "ember-validations": "2.0.0-alpha.4",
    "ember-welcome-page": "^1.0.1",
    "ember-wormhole": "0.4.0",
    "emberx-select": "2.0.2",
    "loader.js": "^4.0.1",
    "torii": "0.6.1"
  }
}
```

**Comment by snewcomer** [comment]
@ultimatelocal If you upgrade to `5.0` all should be good!  Feel free to close the issue if 5.0 fixes it for ya! ✌️

**Comment by snewcomer** [comment]
Closing for now! Feel free to re-open if you are experiencing this or other errors!
