### ISSUE TITLE
Deprecation handlerInfo.handler - [deprecation id: remove-handler-infos]

### ISSUE THREAD

**Issue by charuwts** [ronco/ember-cli-meta-tags#76]
This may be planned to be addressed before the deprecation takes placed, but thought I'd mention I'm getting this deprecation warning and it back traces to head-tags.js line 37

See https://emberjs.com/deprecations/v3.x#toc_remove-handler-infos for more details.

https://github.com/ronco/ember-cli-meta-tags/blob/6b14673dec4c43fb4d27fc06785aef60a3052107/addon/services/head-tags.js#L37

```DEPRECATION: You attempted to read "handlerInfo.handler" which is a private API that will be removed. [deprecation id: remove-handler-infos] See https://emberjs.com/deprecations/v3.x#toc_remove-handler-infos for more details.
        at logDeprecationStackTrace (/tmp/broccoli-9101Dd24O9FCOtwR/out-304-broccoli_merge_trees/assets/@ember/debug/lib/deprecate.js:86:1)
        at HANDLERS.(anonymous function) (/tmp/broccoli-9101Dd24O9FCOtwR/out-304-broccoli_merge_trees/assets/@ember/debug/lib/handlers.js:11:1)
        at raiseOnDeprecation (/tmp/broccoli-9101Dd24O9FCOtwR/out-304-broccoli_merge_trees/assets/@ember/debug/lib/deprecate.js:110:1)
        at HANDLERS.(anonymous function) (/tmp/broccoli-9101Dd24O9FCOtwR/out-304-broccoli_merge_trees/assets/@ember/debug/lib/handlers.js:11:1)
        at invoke (/tmp/broccoli-9101Dd24O9FCOtwR/out-304-broccoli_merge_trees/assets/@ember/debug/lib/handlers.js:20:1)
        at deprecate (/tmp/broccoli-9101Dd24O9FCOtwR/out-304-broccoli_merge_trees/assets/@ember/debug/lib/deprecate.js:146:1)
        at ResolvedRouteInfo.get (/tmp/broccoli-9101Dd24O9FCOtwR/out-304-broccoli_merge_trees/assets/@ember/-internals/routing/lib/system/router.js:72:1)
        at handlerInfos.forEach.handlerInfo (/tmp/broccoli-9101Dd24O9FCOtwR/out-304-broccoli_merge_trees/assets/addon-tree-output/ember-cli-meta-tags/services/head-tags.js:31:1)
        at Array.forEach (native)
        at Class.collectHeadTags (/tmp/broccoli-9101Dd24O9FCOtwR/out-304-broccoli_merge_trees/assets/addon-tree-output/ember-cli-meta-tags/services/head-tags.js:30:1)
        at Class.on (/tmp/broccoli-9101Dd24O9FCOtwR/out-304-broccoli_merge_trees/assets/addon-tree-output/ember-cli-meta-tags/initializers/router-head-tags.js:19:1)
        at sendEvent (/tmp/broccoli-9101Dd24O9FCOtwR/out-304-broccoli_merge_trees/assets/@ember/-internals/metal.js:182:1)
        at Class.trigger (/tmp/broccoli-9101Dd24O9FCOtwR/out-304-broccoli_merge_trees/assets/@ember/-internals/runtime/lib/mixins/evented.js:64:1)
        at /tmp/broccoli-9101Dd24O9FCOtwR/out-304-broccoli_merge_trees/assets/@ember/-internals/routing/lib/system/router.js:244:1
        at invokeWithOnError (/tmp/broccoli-9101Dd24O9FCOtwR/out-304-broccoli_merge_trees/assets/backburner.js:255:1)
        at Queue.flush (/tmp/broccoli-9101Dd24O9FCOtwR/out-304-broccoli_merge_trees/assets/backburner.js:168:1)
        at DeferredActionQueues.flush (/tmp/broccoli-9101Dd24O9FCOtwR/out-304-broccoli_merge_trees/assets/backburner.js:320:1)
        at Backburner._end (/tmp/broccoli-9101Dd24O9FCOtwR/out-304-broccoli_merge_trees/assets/backburner.js:750:1)
        at Backburner._boundAutorunEnd (/tmp/broccoli-9101Dd24O9FCOtwR/out-304-broccoli_merge_trees/assets/backburner.js:487:1)
        at process._tickCallback (internal/process/next_tick.js:109:7)
DEPRECATION: You attempted to read "handlerInfo.handler" which is a private API that will be removed. [deprecation id: remove-handler-infos] See https://emberjs.com/deprecations/v3.x#toc_remove-handler-infos for more details.
        at logDeprecationStackTrace (/tmp/broccoli-9101Dd24O9FCOtwR/out-304-broccoli_merge_trees/assets/@ember/debug/lib/deprecate.js:86:1)
        at HANDLERS.(anonymous function) (/tmp/broccoli-9101Dd24O9FCOtwR/out-304-broccoli_merge_trees/assets/@ember/debug/lib/handlers.js:11:1)
        at raiseOnDeprecation (/tmp/broccoli-9101Dd24O9FCOtwR/out-304-broccoli_merge_trees/assets/@ember/debug/lib/deprecate.js:110:1)
        at HANDLERS.(anonymous function) (/tmp/broccoli-9101Dd24O9FCOtwR/out-304-broccoli_merge_trees/assets/@ember/debug/lib/handlers.js:11:1)
        at invoke (/tmp/broccoli-9101Dd24O9FCOtwR/out-304-broccoli_merge_trees/assets/@ember/debug/lib/handlers.js:20:1)
        at deprecate (/tmp/broccoli-9101Dd24O9FCOtwR/out-304-broccoli_merge_trees/assets/@ember/debug/lib/deprecate.js:146:1)
        at ResolvedRouteInfo.get (/tmp/broccoli-9101Dd24O9FCOtwR/out-304-broccoli_merge_trees/assets/@ember/-internals/routing/lib/system/router.js:72:1)
        at handlerInfos.forEach.handlerInfo (/tmp/broccoli-9101Dd24O9FCOtwR/out-304-broccoli_merge_trees/assets/addon-tree-output/ember-cli-meta-tags/services/head-tags.js:31:1)
        at Array.forEach (native)
        at Class.collectHeadTags (/tmp/broccoli-9101Dd24O9FCOtwR/out-304-broccoli_merge_trees/assets/addon-tree-output/ember-cli-meta-tags/services/head-tags.js:30:1)
        at Class.on (/tmp/broccoli-9101Dd24O9FCOtwR/out-304-broccoli_merge_trees/assets/addon-tree-output/ember-cli-meta-tags/initializers/router-head-tags.js:19:1)
        at sendEvent (/tmp/broccoli-9101Dd24O9FCOtwR/out-304-broccoli_merge_trees/assets/@ember/-internals/metal.js:182:1)
        at Class.trigger (/tmp/broccoli-9101Dd24O9FCOtwR/out-304-broccoli_merge_trees/assets/@ember/-internals/runtime/lib/mixins/evented.js:64:1)
        at /tmp/broccoli-9101Dd24O9FCOtwR/out-304-broccoli_merge_trees/assets/@ember/-internals/routing/lib/system/router.js:244:1
        at invokeWithOnError (/tmp/broccoli-9101Dd24O9FCOtwR/out-304-broccoli_merge_trees/assets/backburner.js:255:1)
        at Queue.flush (/tmp/broccoli-9101Dd24O9FCOtwR/out-304-broccoli_merge_trees/assets/backburner.js:168:1)
        at DeferredActionQueues.flush (/tmp/broccoli-9101Dd24O9FCOtwR/out-304-broccoli_merge_trees/assets/backburner.js:320:1)
        at Backburner._end (/tmp/broccoli-9101Dd24O9FCOtwR/out-304-broccoli_merge_trees/assets/backburner.js:750:1)
        at Backburner._boundAutorunEnd (/tmp/broccoli-9101Dd24O9FCOtwR/out-304-broccoli_merge_trees/assets/backburner.js:487:1)
        at process._tickCallback (internal/process/next_tick.js:109:7)
```

**Comment by CvX** [comment]
PR #75 (released in 5.2.0) was supposed to take care of this deprecation.

What ember-source and ember-cli-meta-tags versions is your application using?

**Comment by charuwts** [comment]
"ember-source": "~3.7.0",
"ember-cli-meta-tags": "^5.2.0",

**Comment by charuwts** [comment]
Your PR does not appear to make any changes to the use of handlerInfo.handler

**Comment by CvX** [comment]
Oh, it's not my PR, it was made by @snewcomer. And it did change the source handlerInfo: https://github.com/ronco/ember-cli-meta-tags/blob/6b14673dec4c43fb4d27fc06785aef60a3052107/addon/services/head-tags.js#L26-L38

Personally, I haven't tested that change in my apps yet…

**Comment by charuwts** [comment]
Line 37 still uses the private method of handlerInfo

**Comment by charuwts** [comment]
I don't know enough about the handlerInfo to know what's not being handled correctly. But please let me know if I can provide any further info to debug the problem.
